version: "3"

services:
  api:
    build: .
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      PORT: 3333
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres
    restart: always
    container_name: PostgreSQL
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data
