version: "3"

services:
  api:
    build: .
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://docker:admin@localhost:5432/habitsdb
      PORT: 3333
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres
    restart: always
    container_name: PostgreSQL
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: docker
      POSTGRES_DB: habitsdb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
